dir: /mnt/data/CREMCOMICSdo001/rpinto/TranscriptionRT/
star_fusion_container: 24151346-7451-3fa1-bb21-15a8d3e3808e
star_fusion_parameters: --CPU 12 --genome_lib_dir /mnt/data/CREMCOMICSdo001/rpinto/TranscriptionRT/annotation/GRCh38_gencode_v31_CTAT_lib_Oct012019.plug-n-play/ctat_genome_lib_build_dir --no_annotation_filter --no_single_fusion_per_breakpoint 
annotation_ref: loci_annotation.bed
DoGFindercontainer: d8ad619d-ab56-33de-a6d7-9dddd2299695
DogFinderOptions: -mode W -w 500 
samples:
- 4712
- 5402
- 5461
- 5465
- 5470
- 5580
- 5584
- 5709
- 5636
- 5681
- 6087
- 6088
- 4863
- 5452
- 5453
- 5454
- 5463
- 5467
- 5468
Get_DoGs_rpkm_options: 
out_dir: TCGA_samples/starfusion_results/
chromsizes: annotation/chr_chromsizes.hg38genome